---
# --------------------------- #
#   User Site Configuration   #
# --------------------------- #

url: http://www.topbug.net
title: Hong Xu
subtitle: Hong's Personal Technology Blog
author: Hong Xu

recent_posts: 10 # Posts in the sidebar Recent Posts section

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
markdown: redcarpet
redcarpet:
  extensions: 
    - no_intra_emphasis
    - strikethrough
    - autolink
    - superscript
    - smart

# To change the layout's default sidebar Add a new sidebar source/_includes/sidebars/your_sidebar.html
# then make changes below, eg. post_sidebar: your_sidebar.html
blog_index_sidebar: my_main_sidebar.html
page_sidebar: my_main_sidebar.html
post_sidebar: my_main_sidebar.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Javascript social buttons often generate lots of http requests and may track your viewer's browsing history
# Show respect for privacy and bandwidth with simple links for Twitter, Facebook and Google Plus.
respectfully_social: true

# Github repositories
github_user: xuhdev
github_repo_count: 10
github_show_profile_link: true
github_skip_forks: false

# Twitter
twitter_user:
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: false
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
google_plus_user: xuhdev
google_plus_hidden: true
google_plus_image_size: 32

# Use comment
use_comments: true

# Disqus Comments
disqus_short_name: xuhdev-homepage
disqus_show_comment_count: true
disqus_developer: 0

# Google Analytics
google_analytics_tracking_id: UA-29984794-1

# Gaug.es Analytics
gauges_analytics_tracking_id:

# Facebook Like
facebook_like: false
